spring :
  datasource :
    url : "jdbc:mysql://localhost:3307/vgc"
    username : root
    password : hehe2003

path :
  pathRoot : D:\Stu\fileHandle


encodeKey :
  key : +YB8Wfu03MT2MhWHg6/vyr3d9lOU76np+BgTlhfROKM=